// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4BaFpjQ6UmYOlVtly-wAYPsiTiV9ojPQ',
    appId: '1:391024164188:web:d77dbd245188b07159d599',
    messagingSenderId: '391024164188',
    projectId: 'voxbox-aff8f',
    authDomain: 'voxbox-aff8f.firebaseapp.com',
    storageBucket: 'voxbox-aff8f.appspot.com',
    measurementId: 'G-MWSKEJN78X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyAl855Dp_use673b0WZq6qiuzP-iegKw',
    appId: '1:391024164188:android:4e123d5663ddcfef59d599',
    messagingSenderId: '391024164188',
    projectId: 'voxbox-aff8f',
    storageBucket: 'voxbox-aff8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARPdfZPLg4QylDLeWaeVPi60j3Ev6XDgY',
    appId: '1:391024164188:ios:8733c5e78e9fc78f59d599',
    messagingSenderId: '391024164188',
    projectId: 'voxbox-aff8f',
    storageBucket: 'voxbox-aff8f.appspot.com',
    iosClientId: '391024164188-rq0cj2siqr6addprl7dmd9dd2mn87ek3.apps.googleusercontent.com',
    iosBundleId: 'com.example.voxbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARPdfZPLg4QylDLeWaeVPi60j3Ev6XDgY',
    appId: '1:391024164188:ios:8733c5e78e9fc78f59d599',
    messagingSenderId: '391024164188',
    projectId: 'voxbox-aff8f',
    storageBucket: 'voxbox-aff8f.appspot.com',
    iosClientId: '391024164188-rq0cj2siqr6addprl7dmd9dd2mn87ek3.apps.googleusercontent.com',
    iosBundleId: 'com.example.voxbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4BaFpjQ6UmYOlVtly-wAYPsiTiV9ojPQ',
    appId: '1:391024164188:web:1c5a408d3342447859d599',
    messagingSenderId: '391024164188',
    projectId: 'voxbox-aff8f',
    authDomain: 'voxbox-aff8f.firebaseapp.com',
    storageBucket: 'voxbox-aff8f.appspot.com',
    measurementId: 'G-CBC6HPX1EJ',
  );

}